#!/usr/bin/python

import sys
symbol = sys.argv[1]
buf = sys.stdin.read()

sys.stdout.write("/* This file is automatically generated. */\n\n")
sys.stdout.write("unsigned char %s[%d] = {" % (symbol, len(buf)))
for offs, ch in enumerate(buf):
	if offs % 16 == 0:
		sys.stdout.write("\n\t")
	sys.stdout.write("0x%02x," % ord(ch))
sys.stdout.write("\n};\n")
